codx-junior scripts fixes

diff --git a/codx-junior b/codx-junior
--- a/codx-junior
+++ b/codx-junior
@@ -17,17 +17,27 @@ fi
 tail -n 30000 $LOGFILE > $LOGFILE
 exec > >(sudo tee -a $LOGFILE) 2>&1
 
-# Ensure ./pids directory exists
-mkdir -p ./pids
+# Apps PIDs
+API_PID=$(pgrep -f "codx.junior.main:app")
+CLIENT_PID=$(pgrep -f "codx-junior/client/node_modules/.bin/vite")
+OLLAMA_PID=$(pgrep -f "ollama")
+NOVNC_PID=$(pgrep -f "vnc ${CODX_JUNIOR_DISPLAY}")
+
+mkdir -p ./logs
 
 function kill_apps() {
-  for pid_file in ./pids/*.pid; do
-    if [ -f "$pid_file" ]; then
-      pid=$(cat "$pid_file")
-      kill -9 "$pid" || true
-      rm "$pid_file"
-    fi
-  done
+  echo "Stop api pid: ${API_PID}"
+  kill ${API_PID} || true
+  
+  echo "Stop client pid: ${CLIENT_PID}"
+  kill ${CLIENT_PID} || true
+  
+  echo "Stop ollama pid: ${OLLAMA_PID}"
+  kill ${OLLAMA_PID} || true
+  
+  echo "Stop noVNC pid: ${NOVNC_PID}"
+  kill ${NOVNC_PID} || true
+
 }
 
 # Function to display help information
@@ -74,8 +84,28 @@ function status() {
 }
 
 # Function to show the tail of the logs file
+function show_log() {
+  echo "Logs for $1 PID $2"
+  tail -n 100 -f ./logs/$1
+}
 function show_logs() {
-    tail -n 100 -f $LOGFILE
+    case "$1" in
+    api)
+        show_log api ${API_PID}
+        ;;
+    client)
+        show_log client ${CLIENT_PID}
+        ;;
+    ollama)
+        show_log ollama ${OLLAMA_PID}
+        ;;
+    novnc)
+        show_log novnc ${NOVNC_PID}
+        ;;
+    *)
+        echo "Invalid command. Use 'logs' to see available commands."
+        ;;
+esac
 }
 
 # Function to simulate running the application
@@ -93,31 +123,34 @@ function run_codx_apps() {
     run_api
     run_client
     run_ollama
+    run_noVNC
 }
 
 function run_code_server() {
     echo "Run code server"
-    code-server --bind-addr=0.0.0.0:${CODX_JUNIOR_CODER_PORT} --auth=none >> $LOGFILE 2>&1 &
-    echo $! > ./pids/code-server.pid
+    code-server --bind-addr=0.0.0.0:${CODX_JUNIOR_CODER_PORT} --auth=none >> ./logs/cod-derver 2>&1 &
 }
 function run_api() {
     echo "Run API"
-    bash "${CODX_JUNIOR_PATH}/scripts/run_api.sh" >> $LOGFILE 2>&1 &
-    echo $! > ./pids/api.pid
+    bash "${CODX_JUNIOR_PATH}/scripts/run_api.sh" >> ./logs/api 2>&1 &
 }
 function run_client() {
     echo "Run client"
-    bash "${CODX_JUNIOR_PATH}/scripts/run_client.sh" >> $LOGFILE 2>&1 &
-    echo $! > ./pids/client.pid
+    bash "${CODX_JUNIOR_PATH}/scripts/run_client.sh" >> ./logs/client 2>&1 & 
 }
 function run_ollama() {
     echo "Run ollama"
-    bash "${CODX_JUNIOR_PATH}/scripts/run_ollama.sh" >> $LOGFILE 2>&1 &
-    echo $! > ./pids/ollama.pid
+    bash "${CODX_JUNIOR_PATH}/scripts/run_ollama.sh" >> ./logs/ollama 2>&1 &
+}
+function run_noVNC() {
+    echo "Run noVNC"
+    bash "${CODX_JUNIOR_PATH}/scripts/run_noVNC.sh" >> ./logs/novnc 2>&1 &
 }
 
+COMMAND=$1
+shift
 # Check the command line argument
-case "$1" in
+case "$COMMAND" in
     stop)
         stop_codx
         ;;
@@ -134,7 +167,7 @@ case "$1" in
         status
         ;;
     logs)
-        show_logs
+        show_logs $@
         ;;
     *)
         echo "Invalid command. Use 'help' to see available commands."
